### ISSUE TITLE
Search results aren't translated by language picker

### ISSUE THREAD

**Issue by topialla** [LabHive/LabHive#138]
When searching for sth and then changing the language, the results content doesn't change. When changing the language and going back and forth (ie refreshing?) the results are translated

**Comment by Kavakuo** [comment]
I would give this a wontfix... This is how the search results are built together. There is no easy fix for this. Only possible solution, with a low overhead, would be to refresh the site ALWAYS when you switch the languages, don't know if this is good at all.

The language selection is persisted in the browser, so most of the users will switch the language exactly one time. I think it is pretty unlikely that this will happen in the search.

But @frwms might have another opinion about this.

**Comment by frwms** [comment]
As discussed, another way could be to write the currently selected search parameters in the URL and force a global refresh on the language switch. Just make a warning when changing language while using the registration form.

Added bonus effect: users can send search queries between each other: "Hey colleague XY, check out how many volunteers are meeting our requirements!" :)

**Comment by topialla** [comment]
It would anyways be great, if we could have a "list" export. So ticking all the interesting people and downloading an excel file, or just copying email-adresses, so users can write to a selected group of volunteers. Of course in the end a messaging system through the platform would be perfect, but for now this low tech approach might help enough? Of course this opens a door to possible spam and we don't know if the help ever arrived...
