### ISSUE TITLE
We need to have new wordings for the skills

### ISSUE THREAD

**Issue by topialla** [LabHive/LabHive#139]
These are just too bulky in the results:

- (Pre-)Processing of clinical samples
- Vor/Aufbereitung klinischer Proben

- Work with RNA (esp. isolation with kit)
- Arbeit mit RNA (insbes. Isolation mit Kit)

They should have a short form in the results.
Or the search results should be shown more nicely, but still its a lot of text when screening results.

**Comment by LisaR1** [comment]
Here are my suggestions to shorten it a bit but keep the meaning:
- clinical sample analysis
- Analyse klinischer Proben
- RNA Isolation
- RNA isolation
RNA isolation means that the person also has experience on how to work with RNA. So that should be enough for this.
What do you think?

**Comment by topialla** [comment]
Thanks @LisaR1 let's do it like this (Jan Baumann preferred this wording in the talk today)
- clinical sample processing
- Arbeit mit klinischen Proben
- RNA Isolation
- RNA isolation

**Comment by topialla** [comment]
Implemented this in Weblate @Kavakuo Hope I did it correctly. The "@" syntax to refer to other things is nice. Is this somewhere documented?

**Comment by Kavakuo** [comment]
Looks good to me.

Documentation how this works is available here:
[https://kazupon.github.io/vue-i18n/guide/messages.html#linked-locale-messages](https://kazupon.github.io/vue-i18n/guide/messages.html#linked-locale-messages)
