### ISSUE TITLE
We need more precise wording for the qualification

### ISSUE THREAD

**Issue by topialla** [LabHive/LabHive#142]
The Qualification wording is imprecise. Some people have completed a PhD, some don't. If I tick PostDoc on the registration, and they look for a PhD, they won't find me, which is bad, because I should be able to do the same work, I'm just not a PhD student any more.

We could state the level as: Tick all the steps you went through, or are currently in?
I'm not sure how to solve this, but we should discuss this again. Maybe I find the time to look at other places, where sth similar is requested.

**Comment by LisaR1** [comment]
Well we could leave postdoc out and say tick your highest degree? Then that would mean ticking MSc means you finished a master and if you tick PhD you finished the PhD?

**Comment by topialla** [comment]
Yes, but Group leader isn't a degree. We could add Professor though.

And also MTLA should be MTA/MTLA (a question today, and makes sense to me).
Doktorrand:in ist auch kein Grad, aber eine wichtige Stufe. 
Letztendlch brauchen wir eben die Abfrage nach "wie vielen Jahren Laborerfahrung" wohl doch.

@frwms Wie bekommen wir die Leute dazu, möglichst immer alle Boxen zu ticken, die zutreffend sind?

**Comment by topialla** [comment]
Auf lange Sicht, oder in "Profil vervollständigen" evtl auch hinter der Stufe noch ein Freitextfeld/Dropdownbox für/mit Studienrichtungen.

**Comment by topialla** [comment]
issue #184 would close this @Kavakuo
