### ISSUE TITLE
Twitter/GitHub icons missing on iPhone

### ISSUE THREAD

**Issue by Kavakuo** [LabHive/LabHive#147]
Social media icons are missing on mobile safari.

**Comment by frwms** [comment]
Showing up for me. They fold into the next row and are easy to miss. Maybe it already helps to decrease the WirVsVirus logo in size on smaller devices so it doesn't draw so much attention?

**Comment by Kavakuo** [comment]
Oh lol, my adblocker blocked them. Wtf, they are just normal `a` elemtents... :D 
I think the size is fine.
