### ISSUE TITLE
Footer is broken on IE11

### ISSUE THREAD

**Issue by Kavakuo** [LabHive/LabHive#150]
The footer is sticked to the bottom of the current browser window and not to the bottom of the website.
![Bildschirmfoto 2020-05-12 um 23 38 17](https://user-images.githubusercontent.com/7912480/81748175-a9f4d480-94a9-11ea-99d6-08b3ab92b0ce.png)

**Comment by topialla** [comment]
I think this was fixed actually, just checked, and for me it works :-)
