### ISSUE TITLE
Ammend disclaimer on dev.labhive.de

### ISSUE THREAD

**Issue by topialla** [LabHive/LabHive#187]
The disclaimer on dev.labhive.de should have a link to the acutal live version now. We gave the dev-link to some people in the past, and if they should arrive there for what ever reason, they should be made aware of the live version.

Suggestions: (please add better termini, if I'm not aware of them ;-) )

Only for test purposes, does not contain real data.
Live Version at https://labhive.de

Dient nur zu Testzwecken, enthält keine echten Daten!
Aktuelle Version unter https://labhive.de

**Comment by Kavakuo** [comment]
You can edit this in weblate yourself, go for it ;)

**Comment by topialla** [comment]
done! Do I have to push a button, or will it update on its own?

**Comment by topialla** [comment]
@Kavakuo I tried again with html formatting around the link. Does this work?

**Comment by topialla** [comment]
It does :-)
