### ISSUE TITLE
Press page custom text

### ISSUE THREAD

**Issue by JoRichers** [LabHive/LabHive#214]
The subpage "press" currently has the "landingpage.top.mainTitle". A custom text would be preferred: https://dev.labhive.de/#/press

What would be the best way to allow for flexibility? Can we define a new identifier, that the text could be easily changed through weblate?

<img width="1024" alt="grafik" src="https://user-images.githubusercontent.com/66110610/84175683-99238880-aa80-11ea-8a19-0e841fb8d76d.png">

**Comment by Kavakuo** [comment]
Yeah, this is possible in Weblate. But the new identifier must updated in the HTML code. So you can prepare everything in Weblate (adding a new identifier with the coorect texts) and ping me after that. Then I can swap out the identifiers in the HTML code :)
