### ISSUE TITLE
Register as translator

### ISSUE THREAD

**Issue by comradekingu** [LabHive/LabHive#277]
Hello, how can I sign up as a translator? The nb_NO translation is quite grim and could do with some improvements.
https://weblate.labhive.de/ asks for a pass and username.

**Comment by topialla** [comment]
Hi @comradekingu ! 
We would be delighted if you could help us out. How can I sent you the login data? 
Your website seems to be unavailable, so I'm not sure if the Mailadress still is active :-)
Bests, Tobi

**Comment by comradekingu** [comment]
@topialla e-mail works just fine. Website stopped working a few days ago, haven't bothered to check.

**Comment by topialla** [comment]
@comradekingu just sent you the login data. Looking forward to your help. Thanks a lot in advance! :-)
