### ISSUE TITLE
Button "Nicht mehr Verfügbar" is quite misleading, if one doesn't know its function

### ISSUE THREAD

**Issue by topialla** [LabHive/LabHive#285]
When a Diagnostic Lab comes to the page, the button "Nicht mehr verfügbar" is misleading.
Users are actively discouraged from contacting them. (I myself was just fooled). Can we please have a hotfix and add an explanatory sentence above the button? Or just a small green text link, that opens a little popup where the button is displayed?

"Falls die Person nicht reagiert, sagen Sie uns bitte bescheid, dann kümmern wir uns"

"If the person doesn't reply within 3 business days, please tell us, so we can take care of it."

**Comment by topialla** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Button "Nicht mehr verfügbar" is misleading, add small explanatory text](https://trello.com/c/GLE6YqqA/19-button-nicht-mehr-verf%C3%BCgbar-is-misleading-add-small-explanatory-text)

**Comment by JoRichers** [comment]
I would say the button text should be adjusted to "Inaktivität melden" "Report inactivity" or removed completely to avoid  confusion.
