### ISSUE TITLE
Bug in base64 decoding of JWT

### ISSUE THREAD

**Issue by iphoneintosh** [LabHive/LabHive#319]
Hey there,

I stumbled across a small bug in the JWT parser in the [http.js](https://github.com/LabHive/LabHive/blob/dev/labshare-client/src/http.js#L20) file. The following code is used to retrieve the JWT from localStorage and parse it:

```js
let token = localStorage.getItem('authToken')
let payload = JSON.parse(atob(token.split(".")[1]))
```

The `atob` function is used to base64-decode the JWT. However, the JWT is encoded in base64url, which modifies base64 in the following way:

- Replaces "+" by "-" (minus)
- Replaces "/" by "_" (underline)
- Does not require a padding character

So if the JWT body of the `authToken` contains, i.e., a "-" (minus) character, the `atob` function throws an error, resulting in the `authToken` being deleted. If the user chooses an email address (contained within the JWT body) that leads to a "-" or "_" character in the encoded JWT, the user cannot login since the token is always deleted.

There are multiple ways of fixing this, i.e., use an appropriate base64url decoder or simply convert base64url to base64 before feeding it to the `atob` function.

**Comment by Kavakuo** [comment]
Thanks for the hint, should be fixed.
