### ISSUE TITLE
Showing shortforms of BSL skills in search result cards

### ISSUE THREAD

**Issue by frwms** [LabHive/LabHive#79]
We need to show shortforms of the BSL skill labels in the search result cards for better scalability. I already added them in the translations (bs1lShort, bsl2Short, bsl3Short, bsl4Short) but didn't want to push it too far with blindly (i. e. without working search results on my local build) changing anything more. 😁 

Can you take care of this Philipp? I'm also interested in a short explanation of how this is set up in case I do need to change it again in the future.

**Comment by Kavakuo** [comment]
Can you have a look @topialla @frwms? So I basically changed the displaying of `BSL` skills in the search results card. If you think this is ok close the issue @topialla :)

**Comment by frwms** [comment]
Sorry, I missed this. Looks fine to me! Paging @topialla in case he also missed the notification 😄

**Comment by topialla** [comment]
I actually now discovered the notification feature in git hub tbh ;-p
