### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by frwms** [LabHive/LabHive#81]
Before we go public, we should consider updating the readme of this repo with some of the more recent texts and maybe some updated technical details. What's your take on that @topialla & @Kavakuo?

**Comment by Kavakuo** [comment]
Totally agree with that. Let's wait for the half pager Eleonora and Jo are writing :D

**Comment by Kavakuo** [comment]
Updated it already with #85 to explain the structure of the repo and I added the text from the EuVsVirus Hackathon.

**Comment by Kavakuo** [comment]
If you think that we still need this before the launch, add the MVP milestone to the issue. Otherwise close the issue, please :)
