### ISSUE TITLE
Secondary Button Active State

### ISSUE THREAD

**Issue by Kavakuo** [LabHive/LabHive#92]
Active state of secondary button is currently green, this should be grey or something like this. The state design is missing in Figma as well.

**Comment by frwms** [comment]
Do we currently have a case where we have an active secondary button? Would, of course, be good for the future anyways, just wondering right now.

**Comment by Kavakuo** [comment]
The back button in the registration forms :)

**Comment by frwms** [comment]
Added directly in code as Figma is still down.
