### ISSUE TITLE
Text-Input Height

### ISSUE THREAD

**Issue by Kavakuo** [LabHive/LabHive#93]
Height of the text fields can be optimized. Current implementation has a height of 50px, in Figma the Text inputs have a height of 40px, something in the middel is optimal I guess.
To implement the design we need the font-sizes and paddings of the placeholder when the text field is focused and not.

**Comment by frwms** [comment]
I will fix this directly in code and update the design next weekend as I need to rescale the whole Design in Figma to match our new font-sizes, which is a time-consuming and tedious task. 😐 Hopefully not too time-consuming and my auto-layout work pays off 😬
